apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: timeoff-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - develcloud.net
    secretName: timeoff-tls
  rules:
    - host: develcloud.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: timeoff-helm-timeoff
                port: 
                  number: 3000