name: DEPLOY_Dev_tiemoff

on:
  push:
    branches: ["**"]

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'read'
    steps:
    - name: Downloading code
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/448231748581/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
        service_account: 'svc-github-actions@big-liberty-373120.iam.gserviceaccount.com'
        project_id: 'big-liberty-373120'

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}